# Generated by Django 4.2.16 on 2024-11-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="image",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="course",
        ),
    ]
