# Generated by Django 4.2.16 on 2024-11-06 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_quiz_course_remove_quiz_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.subject'),
        ),
    ]
