# Generated by Django 4.2.16 on 2024-11-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_quiz_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="mocktest",
            name="questions",
            field=models.ManyToManyField(
                related_name="mock_tests", to="core.questions"
            ),
        ),
    ]
