# Generated by Django 4.2.16 on 2024-11-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mocktestsubjectconfig_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizname',
            name='No_of_Questions',
            field=models.IntegerField(default=10),
        ),
    ]
